name: ci
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: make fmt-check
      - run: make CC=${{ matrix.cc }}
      - run: make test
